version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: error_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: error_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
